-- 050_golf_polos_batch_2.sql
-- 2026-08-31. Golf polos batch 2: tops_61 - tops_99. Thirty-nine garments, 82 photographs.
--
-- COUNT, done before a single row was written. 86 files in Downloads\Golf Polos: 83 JPG + 3 PNG.
-- Four of the JPGs (the 06:22 shots) are BYTE-IDENTICAL by MD5 to photos already filed as
-- tops_57_..._01_hanger / _02_label and tops_58_..._01_hanger / _02_label. They are batch-1
-- re-downloads, excluded. The three PNGs are not screenshots: they are one garment (flat-lay,
-- neck label, chest detail) - the Bermuda Sands bird-print polo, tops_99.
-- 82 photographs remain. Grouped by shot order into 39 garments: 40 flat-lays and 42
-- label/detail shots, confirmed on a labelled contact sheet before any insert.
--
-- TWO RED PETER MILLAR "INTERCLUB" POLOS, NOT ONE (tops_62 and tops_64). Same white RSGC
-- crown-and-monogram with INTERCLUB beneath, same Summer Comfort neck label. The size tags
-- differ and both were read at full resolution: S on tops_62, M on tops_64. Confirmed with Max
-- before writing. If they ever turn out to be one garment, tops_64 is the one to retire.
--
-- ONE FLAT-LAY IS TWO FRAMES. tops_71 was shot twice 0.2s apart (070405412 / 070405597). Both
-- are filed, as _01_hanger and _02_hanger.
--
-- SIZING. The batch-1 rule holds and is now much better evidenced. Every US golf brand that
-- could be read comes in S or M and nothing is larger: FootJoy S/M/M/M, Nike Golf S and S,
-- Peter Millar S/M/M, Fairway & Greene M, Greyson S, G/FORE M, Glenmuir S/M/M/S, adidas S.
-- Buy S in US golf brands, M in generic and Asian-sized. Eighteen sizes could not be read and
-- are recorded as unknown rather than inferred from the rule.
--
-- CLUBS. This batch is the first that is NOT mostly Royal Sydney. Home clubs: eleven RSGC and
-- two Woollahra ("REPRESENTATIVE", tops_78 and tops_91) - no restriction anywhere. Visitor
-- souvenirs, which carry another club's crest and should be worn accordingly: Royal Melbourne
-- (tops_73), Barnbougle Lost Farm (tops_72), Barnbougle Dunes (tops_97), Ocean Dunes King
-- Island (tops_96), Golf Club Barbaroux (tops_92), Camiral (tops_94), Bonville (tops_95),
-- Links Hope Island (tops_99), and the Masters (tops_85).
--
-- BRANDS NOT GUESSED. Nine rows carry no brand: tops_61, tops_72, tops_73, tops_78, tops_80,
-- tops_86, tops_92, tops_93 and the second Nike-style chest mark on tops_71. In each case the
-- neck label is either absent from the frame, blacked out, or unreadable at full resolution
-- after zoom. Following tops_58: do not guess a brand into these rows.
--
-- ONE I NEARLY GOT WRONG. tops_94 reads as a Nike swoosh on a contact sheet. At full
-- resolution the neck label is G/FORE, size M, and what looked like a swoosh is a camo shape.
-- The chest reads CAMIRAL. Zoom before naming a brand off a thumbnail.
--
-- COLOUR. Measured against the white table in frame, batch-1 method, with ONE CORRECTION that
-- matters: the white-point candidates now EXCLUDE the garment's own box. On the first pass the
-- pale garments were their own white reference, which turned the khaki FootJoy neutral grey and
-- the peach Under Armour into a warm grey. The reference is the table, never the garment.
-- Ten near-white garments are still set by judgement and flagged derived, exactly as tops_52
-- and tops_53 were: the method measures shadow on a white piqué, not colour.
--
-- CONDITION. Asserted only from the flat, evenly-lit flat-lays, per the hats lesson. Nothing
-- was inspected by hand. Two rows carry a possible-mark note rather than a damage claim.

INSERT INTO items (id, slug, cat_code, name, colour, hex, role_code, neck_raw, cut, material,
                   weight_code, formality_raw, formality_rank, formality_note, fit, condition,
                   verdict_code, verdict_note, scope_code, works_alone, pairs, layer, avoid,
                   notes, no_photo, photo_prefix, retail_prefix, warmth, rain_unsafe, pattern,
                   unconfirmed) VALUES
('tops_61_rose-unbranded-polo','rose-unbranded-polo','Tops','Dusty rose polo (unbranded)','Dusty rose','#AD7782','Mid colour','polo collar','Short-sleeve polo, two-button placket, self collar','Polyester pique','Light','Casual',3,'No club crest','Size M','Good from the flat-lay','Keep','The only dusty rose in the drawer. Reads softer than the three reds and is easier to place.','core',true,'Navy, stone, white, charcoal','-','Red or pink bottoms','Neck label is a size tag only - M, 100% polyester, made in China. NO BRAND MARK ANYWHERE IN FRAME. Not guessed.',false,'tops_61_rose-unbranded-polo','tops_61_rose-unbranded-polo_retail',1,false,'Plain',false),

('tops_62_peter-millar-red-interclub-polo-s','peter-millar-red-interclub-polo-s','Tops','Peter Millar red RSGC Interclub polo (S)','Red','#B31D3A','Statement','polo collar','Short-sleeve polo, three-button placket, self collar, side vents','Summer Comfort performance jersey','Light','Smart-casual',4,'Royal Sydney - home club, no restriction. Team shirt','Size S','Good from the flat-lay','Keep','One of two red Interclub polos. This is the S. Best-made red here.','core',true,'Navy, white, stone, charcoal','-','Red or coral bottoms','PETER MILLAR Summer Comfort, size S. White RSGC crown-and-monogram with INTERCLUB embroidered beneath it on the left chest.',false,'tops_62_peter-millar-red-interclub-polo-s','tops_62_peter-millar-red-interclub-polo-s_retail',1,false,'Plain',false),

('tops_63_fairway-greene-red-rsgc-polo','fairway-greene-red-rsgc-polo','Tops','Fairway & Greene red RSGC polo','Red','#C01C40','Statement','polo collar','Short-sleeve polo, three-button placket, waffle-knit collar','Performance jersey','Light','Smart-casual',4,'Royal Sydney - home club, no restriction','Size M','Good from the flat-lay','Keep','GOLD crest, like tops_54. Gold on red is the better of the two gold pairings.','core',true,'Navy, white, stone, charcoal','-','Red, coral or pink bottoms','FAIRWAY & GREENE, size M, made in the USA - read off the tonal placket transfer. GOLD RSGC crown-and-monogram on the left chest. Waffle-textured collar and cuff.',false,'tops_63_fairway-greene-red-rsgc-polo','tops_63_fairway-greene-red-rsgc-polo_retail',1,false,'Plain',false),

('tops_64_peter-millar-red-interclub-polo-m','peter-millar-red-interclub-polo-m','Tops','Peter Millar red RSGC Interclub polo (M)','Red','#CB1D3F','Statement','polo collar','Short-sleeve polo, three-button placket, self collar, side vents','Summer Comfort performance jersey','Light','Smart-casual',4,'Royal Sydney - home club, no restriction. Team shirt','Size M - the larger of the two Interclub reds','Good from the flat-lay','Keep','The M of the pair. Same shirt as tops_62 a size up; if only one is really owned, retire this row.','core',true,'Navy, white, stone, charcoal','-','Red or coral bottoms','PETER MILLAR Summer Comfort, size M, read at full resolution from the neck label visible in its own flat-lay. White RSGC crown-and-monogram with INTERCLUB beneath.',false,'tops_64_peter-millar-red-interclub-polo-m','tops_64_peter-millar-red-interclub-polo-m_retail',1,false,'Plain',false),

('tops_65_ping-blush-stripe-rsgc-polo','ping-blush-stripe-rsgc-polo','Tops','PING blush stripe RSGC polo','Blush pink with fine white stripe','#EFCFCA','Pale warm','polo collar','Short-sleeve polo, three-button placket, self collar','sensorcool technical jersey','Light','Smart-casual',4,'Royal Sydney - home club, no restriction','Size not read - the PING size tag is folded under a finger in the only label shot','Good from the flat-lay','Keep','The palest thing in the batch and the easiest to wear. Tonal crest, so it never shouts.','core',true,'Navy, stone, white, charcoal','-','Pink or red bottoms','PING sensorcool. Fine white-on-blush stripe; TONAL blush RSGC crown-and-monogram on the left chest. Size unread - measure the chest flat if it matters.',false,'tops_65_ping-blush-stripe-rsgc-polo','tops_65_ping-blush-stripe-rsgc-polo_retail',1,false,'Fine stripe',false),
('tops_66_good-good-coral-floral-polo','good-good-coral-floral-polo','Tops','Good Good coral floral polo','White ground with dense coral and red floral print, magenta collar','#CBACB4','Statement','polo collar','Short-sleeve polo, three-button placket, contrast magenta collar and inner placket','92% polyester / 8% elastane','Light','Casual',2,'Loud print and a novelty brand - social round only, not a guest day','Size MEDIUM','Good from the flat-lay','Keep','The loudest thing in this batch, the way tops_51 was in the last one. Fine on a Saturday.','core',true,'White, stone, navy. Nothing else patterned','-','Any other print, and pink or red bottoms','GOOD GOOD - FIGHTING FOR PAR, size MEDIUM, made in South Korea. Coral floral on white with a solid magenta collar and inner placket.',false,'tops_66_good-good-coral-floral-polo','tops_66_good-good-coral-floral-polo_retail',1,false,'Floral print',false),

('tops_67_under-armour-peach-polo','under-armour-peach-polo','Tops','Under Armour peach polo','Peach','#F8E2D2','Pale warm','polo collar','Short-sleeve polo, three-button placket, self collar','Technical performance jersey','Light','Casual',3,'Brand polo, no club','Size not read - the UA heat-seal is worn and illegible even after zoom','Good from the flat-lay','Keep','Softest colour in the batch. Reads sportier than the Peter Millars but the colour carries it.','core',true,'Navy, stone, white, charcoal','-','Pink, coral or red bottoms','UNDER ARMOUR - logo on the left chest, heat-seal neck print reading THE PERFORMANCE POLO / LE POLO PERFORMANCE / LA CAMISA POLO DE PERFORMANCE. Size unread.',false,'tops_67_under-armour-peach-polo','tops_67_under-armour-peach-polo_retail',1,false,'Plain',false),

('tops_68_peter-millar-white-rsgc-polo-m','peter-millar-white-rsgc-polo-m','Tops','Peter Millar white RSGC polo (M)','White','#F2F1EE','Pale neutral','polo collar','Short-sleeve polo, three-button placket, self collar, side vents','Summer Comfort performance jersey','Light','Smart-casual',4,'Royal Sydney - home club, no restriction','Size M - a size up from tops_52, which is the S','Good from the flat-lay. White, so watch the collar and underarms.','Keep','The M twin of tops_52. Two white Peter Millar RSGC polos in two sizes.','core',true,'Navy, stone, charcoal, coral','-','Nothing significant - white goes under everything','PETER MILLAR Summer Comfort, size M. RED RSGC crest on the left chest, unlike the navy one on tops_52.',false,'tops_68_peter-millar-white-rsgc-polo-m','tops_68_peter-millar-white-rsgc-polo-m_retail',1,false,'Plain',false),

('tops_69_glenmuir-cream-mercerised-polo','glenmuir-cream-mercerised-polo','Tops','Glenmuir cream mercerised polo','Cream','#F1EFE9','Pale neutral','polo collar','Short-sleeve polo, three-button placket, self collar with tartan inner collar stand','Double-mercerised cotton','Light','Smart-casual',4,'Brand polo, no club. The best cotton in the batch','Size M','Creased in the flat-lay but sound; cotton, so it will always need pressing','Keep','The one cotton polo here among a drawer of polyester. Wears better off the course than any of them.','core',true,'Navy, stone, olive, charcoal','-','Nothing significant','GLENMUIR 1891, size M, DOUBLE MERCERISED. Green-and-navy tartan inside the collar stand - the only tartan detail in the wardrobe.',false,'tops_69_glenmuir-cream-mercerised-polo','tops_69_glenmuir-cream-mercerised-polo_retail',1,false,'Plain',false),

('tops_70_footjoy-khaki-polo','footjoy-khaki-polo','Tops','FootJoy khaki polo','Khaki sand','#D6C9B2','Warm neutral','polo collar','Short-sleeve polo, three-button placket, self collar with navy FJ at the collar tip','Technical pique','Light','Smart-casual',3,'Dark navy crest on the left chest, NOT read at full resolution - confirm before assuming it is Royal Sydney','FootJoy Athletic Fit, size S','Good from the flat-lay','Keep','Only warm neutral in the batch and the natural partner for navy or olive shorts.','core',true,'Navy, olive, stone, white','-','Beige or stone bottoms - too close to the shirt','FOOTJOY Athletic Fit, size S. Navy FJ mark on the collar tip. A dark navy crest sits on the left chest; it is not legible in either photograph and has not been named.',false,'tops_70_footjoy-khaki-polo','tops_70_footjoy-khaki-polo_retail',1,false,'Plain',true),
('tops_71_nike-charcoal-piped-polo','nike-charcoal-piped-polo','Tops','Nike Golf charcoal piped polo','Charcoal','#3C4148','Anchor dark','polo collar','Short-sleeve polo, two-button placket, self collar, white contrast piping along the raglan and side seams, mesh back yoke','Dri-FIT technical jersey','Light','Casual',3,'Small pale chest embroidery, not legible - no club asserted','Size S, made in Thailand','Good from the flat-lay','Keep','The sportier of the two Nike charcoals. The white piping is what separates it from tops_88.','core',true,'Navy, stone, white, olive','-','Charcoal or black bottoms','NIKE GOLF DRI-FIT, size S, made in Thailand. White piping down the raglan and side seams and a mesh back yoke. A small pale script embroidery sits on the left chest and could not be read at full resolution - not guessed.',false,'tops_71_nike-charcoal-piped-polo','tops_71_nike-charcoal-piped-polo_retail',1,false,'Plain',false),

('tops_72_barnbougle-lost-farm-charcoal-polo','barnbougle-lost-farm-charcoal-polo','Tops','Barnbougle Lost Farm charcoal polo','Charcoal','#3E424A','Anchor dark','polo collar','Short-sleeve polo, three-button placket, self collar with fine white piping at the collar edge','Technical jersey','Light','Casual',3,'BARNBOUGLE LOST FARM - a visitor souvenir, not a home club. Wear it anywhere except Lost Farm itself','Size not read','Good from the flat-lay','Keep','A course shirt from Tasmania. Quiet enough that the crest is the only thing anyone notices.','core',true,'Stone, navy, white, olive','-','Charcoal or black bottoms','Barnbougle LOST FARM embroidered in white on the left chest. NO BRAND LABEL IN FRAME - the maker is unknown and has not been guessed. Size unread.',false,'tops_72_barnbougle-lost-farm-charcoal-polo','tops_72_barnbougle-lost-farm-charcoal-polo_retail',1,false,'Plain',true),

('tops_73_royal-melbourne-navy-argyle-polo','royal-melbourne-navy-argyle-polo','Tops','Royal Melbourne navy argyle polo','Navy','#313743','Anchor dark','polo collar','Short-sleeve polo, three-button placket, self collar, white argyle diagonals across the body','Technical jersey','Light','Casual',3,'ROYAL MELBOURNE - a visitor souvenir, not a home club. The crest belongs to someone else''s course','Size not read','Good from the flat-lay','Keep','The one argyle in the wardrobe. Loud pattern plus another club''s crest - a social round, not a guest day.','core',true,'Stone, white, khaki','-','Navy bottoms, and anything else patterned','White crown-and-horse crest reading ROYAL MELBOURNE on the left chest, with white argyle diagonals printed across the body. NO BRAND LABEL IN FRAME - not guessed. Size unread. The second photograph is a macro of a hem pocket with a debossed mark that could not be read.',false,'tops_73_royal-melbourne-navy-argyle-polo','tops_73_royal-melbourne-navy-argyle-polo_retail',1,false,'Argyle',true),

('tops_74_footjoy-purple-stripe-rsgc-polo','footjoy-purple-stripe-rsgc-polo','Tops','FootJoy purple stripe RSGC polo','Purple with fine tonal stripe','#645799','Statement','polo collar','Short-sleeve polo, three-button placket, contrast fine-stripe collar and inner placket, white FJ at the collar tip','Technical jersey','Light','Smart-casual',3,'Royal Sydney - home club, no restriction','FootJoy Athletic Fit, size M','Good from the flat-lay','Keep','Only purple in the wardrobe. Strong colour, tonal crest - it works because nothing else competes.','core',true,'Navy, white, stone, charcoal','-','Blue, purple or pink bottoms','FOOTJOY Athletic Fit, size M. Fine white-on-purple striped collar and inner placket, white FJ on the collar tip, TONAL purple RSGC crown-and-monogram on the left chest.',false,'tops_74_footjoy-purple-stripe-rsgc-polo','tops_74_footjoy-purple-stripe-rsgc-polo_retail',1,false,'Fine stripe',false),

('tops_75_sporte-blue-diamond-rsgc-polo','sporte-blue-diamond-rsgc-polo','Tops','Sporte Leisure blue diamond RSGC polo','Mid blue with small navy diamond print','#679DE1','Mid colour','polo collar','Short-sleeve polo, three-button placket, self collar','DRI-SPORTE technical jersey','Light','Smart-casual',3,'Royal Sydney - home club, no restriction','Size M - generic Australian brand, so M is right per the sizing rule','Good from the flat-lay','Keep','The most useful blue here. Print is small enough to read as texture at any distance.','core',true,'Navy, stone, white, charcoal','-','Blue bottoms - the shirt is already the blue','SPORTE LEISURE DRI-SPORTE, size M, made in China. Small navy diamond print on mid blue, navy RSGC crown-and-monogram on the left chest.',false,'tops_75_sporte-blue-diamond-rsgc-polo','tops_75_sporte-blue-diamond-rsgc-polo_retail',1,false,'Diamond print',false),
('tops_76_ralph-lauren-blue-medallion-polo','ralph-lauren-blue-medallion-polo','Tops','Polo Golf Ralph Lauren blue medallion polo','Pale blue with navy and sage medallion print','#AAB5C4','Pattern','polo collar','Short-sleeve polo, two-button placket, self collar in the same print','Cotton-blend jersey','Light','Smart-casual',4,'No club crest - the pony is the only mark','Size not read - the Polo Golf label shows only MADE IN PERU in frame','Good from the flat-lay','Keep','A foulard medallion, which reads dressier than a golf print. The one here that works with chinos off the course.','core',true,'Navy, stone, white','-','Anything else patterned','POLO GOLF RALPH LAUREN, made in Peru. Navy-and-sage medallion foulard on pale blue with the navy pony on the left chest. Size unread.',false,'tops_76_ralph-lauren-blue-medallion-polo','tops_76_ralph-lauren-blue-medallion-polo_retail',1,false,'Medallion print',false),

('tops_77_greyson-pale-print-polo','greyson-pale-print-polo','Tops','Greyson pale print polo','Pale grey-blue tonal print','#B6BAC4','Pattern','polo collar','Short-sleeve polo, two-button placket, contrast printed collar with a pale blue inner stand','Technical jersey','Light','Smart-casual',4,'No club crest','Size S','Good from the flat-lay','Keep','Greyson is the most fashion-led label in the drawer and it shows in the collar. Quiet from three metres, interesting up close.','core',true,'Navy, stone, white, charcoal','-','Anything else patterned','GREYSON, size S. Tonal pale print on the body with a separate navy-and-blue printed collar and a pale blue inner collar stand.',false,'tops_77_greyson-pale-print-polo','tops_77_greyson-pale-print-polo_retail',1,false,'Tonal print',false),

('tops_78_woollahra-white-micro-floral-polo','woollahra-white-micro-floral-polo','Tops','Woollahra Representative white micro-floral polo','White with navy micro-floral print','#EFEFF2','Pattern','polo collar','Short-sleeve polo, three-button placket, self collar','Technical jersey','Light','Smart-casual',4,'WOOLLAHRA GOLF CLUB - REPRESENTATIVE. Home club, no restriction','Size not read - no label photograph was taken for this garment','Good from the flat-lay','Keep','A representative shirt, so it says something about you rather than just where you play. Wear it.','core',true,'Navy, stone, charcoal','-','Anything else patterned','Navy WOOLLAHRA GOLF CLUB crest with REPRESENTATIVE beneath it on the left chest, on a white ground with a small navy floral print. ONLY ONE PHOTOGRAPH EXISTS - no neck label was shot, so brand and size are both unknown and not guessed.',false,'tops_78_woollahra-white-micro-floral-polo','tops_78_woollahra-white-micro-floral-polo_retail',1,false,'Micro floral',true),

('tops_79_private-estate-blue-floral-polo','private-estate-blue-floral-polo','Tops','Private Estate blue floral polo','Pale blue with dense navy floral print','#B6C3D7','Pattern','polo collar','Short-sleeve polo, three-button placket, self collar in the same print','Cotton-blend jersey','Light','Smart-casual',3,'No club crest','Size M','Good from the flat-lay','Keep','Busiest of the three blue prints. Fine on its own, wrong next to anything else patterned.','core',true,'Navy, stone, white','-','Anything else patterned, and blue bottoms','PRIVATE ESTATE, size M. Dense navy floral print over pale blue, collar in the same print.',false,'tops_79_private-estate-blue-floral-polo','tops_79_private-estate-blue-floral-polo_retail',1,false,'Floral print',false),

('tops_80_red-unbranded-polo','red-unbranded-polo','Tops','Red polo (unbranded)','Red','#BA1C3A','Statement','polo collar','Short-sleeve polo, three-button placket, waffle-knit collar, fine grey piping at the shoulder','Technical jersey','Light','Casual',3,'A small dark chest mark that could not be read - no club asserted','Size M/M','Good from the flat-lay','Keep','The fourth red. Plainest of them and the one to wear when the crest would be too much.','core',true,'Navy, white, stone, charcoal','-','Red, coral or pink bottoms','Neck tag reads M/M, MADE IN CHINA and nothing else. NO BRAND MARK ANYWHERE IN FRAME. A small dark navy logo sits on the left chest and is not legible even at full resolution - not guessed.',false,'tops_80_red-unbranded-polo','tops_80_red-unbranded-polo_retail',1,false,'Plain',true),
('tops_81_adidas-grey-yellow-stripe-polo','adidas-grey-yellow-stripe-polo','Tops','adidas grey polo with yellow stripe','Grey with a yellow chest stripe','#86888E','Mid neutral','polo collar','Short-sleeve polo, two-button placket, self collar, single yellow stripe across the chest with a grey marl lower body','puremotion technical jersey','Light','Casual',3,'Brand polo, no club','Size not read - the adidas neck transfer is worn','Good from the flat-lay','Keep','Reads sports-shop rather than club. Range and social rounds.','core',true,'Navy, charcoal, stone','-','Yellow or grey bottoms','ADIDAS puremotion. Grey upper with a single yellow stripe across the chest and a grey marl lower body, adidas wordmark on the left chest. Size unread.',false,'tops_81_adidas-grey-yellow-stripe-polo','tops_81_adidas-grey-yellow-stripe-polo_retail',1,false,'Chest stripe',false),

('tops_82_glenmuir-grey-rsgc-polo','glenmuir-grey-rsgc-polo','Tops','Glenmuir grey RSGC polo','Grey marl','#9898A0','Mid neutral','polo collar','Short-sleeve polo, three-button placket, self collar, white geometric chest panel with pink piping','Performance wicking jersey','Light','Smart-casual',3,'Royal Sydney - home club, no restriction','Size S','Good from the flat-lay','Keep','The pink piping is the only reason this is not another anonymous grey polo.','core',true,'Navy, charcoal, stone, white','-','Grey bottoms','GLENMUIR 1891 PERFORMANCE WICKING, size S. Grey marl body with a white geometric-print chest panel edged in pink, white RSGC crown-and-monogram on the left chest.',false,'tops_82_glenmuir-grey-rsgc-polo','tops_82_glenmuir-grey-rsgc-polo_retail',1,false,'Panel',false),

('tops_83_sporte-green-yoke-polo','sporte-green-yoke-polo','Tops','Sporte Leisure green polo with grey yoke','Bright green with grey shoulder yoke','#53A962','Statement','polo collar','Short-sleeve polo, three-button placket, self collar, contrast grey shoulder yoke','Technical jersey','Light','Casual',3,'Brand polo, no club','Size not read - the Sporte heat-seal shows no size in frame','Good from the flat-lay','Keep','The brightest green in the wardrobe. Strong on a fairway, loud anywhere else.','core',true,'Navy, charcoal, stone, white','-','Green or olive bottoms','SPORTE LEISURE heat-seal at the neck. Bright green body with a grey shoulder yoke. Size unread.',false,'tops_83_sporte-green-yoke-polo','tops_83_sporte-green-yoke-polo_retail',1,false,'Colourblock',false),

('tops_84_royal-sydney-jade-polo','royal-sydney-jade-polo','Tops','Royal Sydney jade polo','Jade green','#38B29F','Statement','polo collar','Short-sleeve polo, two-button placket, self collar','Cotton-blend pique','Light','Smart-casual',4,'Royal Sydney - home club, no restriction. Club''s own label','Size S','Good from the flat-lay','Keep','Club merchandise proper - the crest is on the neck label, not just the chest. Made in Australia, which almost nothing else here is.','core',true,'Navy, stone, white, charcoal','-','Green or teal bottoms','Neck label is the RSGC crown-and-monogram itself, MADE IN AUSTRALIA, size S - the club''s own label rather than a brand''s. Tonal jade crest on the left chest.',false,'tops_84_royal-sydney-jade-polo','tops_84_royal-sydney-jade-polo_retail',1,false,'Plain',false),

('tops_85_masters-dark-green-polo','masters-dark-green-polo','Tops','Masters Collection dark green polo','Dark pine green','#455F5E','Anchor dark','polo collar','Short-sleeve polo, three-button placket, self collar','100% Pima cotton, 60s two-ply mercerised','Light','Smart-casual',4,'AUGUSTA NATIONAL / THE MASTERS - a visitor souvenir and a conspicuous one. Wear it knowing it will be noticed','Size M','Good from the flat-lay','Keep','The most recognisable logo in the wardrobe and the best cotton alongside tops_69. It will get comments.','core',true,'Stone, khaki, white, navy','-','Green or olive bottoms','MASTERS COLLECTION, 60s TWO-PLY MERCERIZED, size M, 100% Pima cotton. The yellow Masters map-and-flagstick logo on the left chest.',false,'tops_85_masters-dark-green-polo','tops_85_masters-dark-green-polo_retail',1,false,'Plain',false),
('tops_86_grey-peru-unbranded-polo','grey-peru-unbranded-polo','Tops','Grey polo (brand unread)','Grey marl','#A8A8AC','Mid neutral','polo collar','Short-sleeve polo, two-button placket, self collar','Cotton-blend pique','Light','Casual',3,'No club crest','Size S, made in Peru','Good from the flat-lay','Keep','Anonymous grey. Useful, forgettable, and the first thing to go if the drawer needs thinning.','core',true,'Navy, charcoal, stone, white','-','Grey bottoms','Two neck tags: a black brand tag that is completely illegible in the photograph, and a size tag reading S, MADE IN PERU. BRAND NOT GUESSED.',false,'tops_86_grey-peru-unbranded-polo','tops_86_grey-peru-unbranded-polo_retail',1,false,'Plain',true),

('tops_87_elord-teal-polo','elord-teal-polo','Tops','ELORD teal polo','Teal','#597583','Mid tone','polo collar','Short-sleeve polo, two-button placket, contrast navy collar and navy sleeve cuffs, wooden buttons','Technical jersey','Light','Casual',3,'A pale blue ring logo on the chest, no club crest','Size not read - the size tag is obscured by a finger in the only label shot','Good from the flat-lay','Keep','Teal with a navy collar is the sharpest colour pairing in the batch. Deserves better than the range.','core',true,'Navy, stone, white, charcoal','-','Teal, blue or green bottoms','ELORD embroidered inside the back of the collar stand - read by un-mirroring the flipped collar in the photograph. Contrast navy collar and cuffs, tan wooden buttons, pale blue ring embroidery on the chest. Size unread.',false,'tops_87_elord-teal-polo','tops_87_elord-teal-polo_retail',1,false,'Plain',false),

('tops_88_nike-charcoal-plain-polo','nike-charcoal-plain-polo','Tops','Nike Golf charcoal plain polo','Charcoal','#3E3F45','Anchor dark','polo collar','Short-sleeve polo, three-button placket, waffle-knit collar, pale blue buttons','Dri-FIT technical pique','Light','Casual',3,'No club crest, no chest mark at all','Size S, made in Vietnam','Good from the flat-lay','Keep','The plainest polo in the wardrobe. Nothing on it anywhere - which is exactly why it is useful.','core',true,'Navy, stone, white, olive, khaki','-','Charcoal or black bottoms','NIKE GOLF DRI-FIT, size S, made in VIETNAM - the country is what separates it from tops_71, which is the Thailand one with white piping. Waffle collar, pale blue buttons, no logo on the body.',false,'tops_88_nike-charcoal-plain-polo','tops_88_nike-charcoal-plain-polo_retail',1,false,'Plain',false),

('tops_89_glenmuir-dark-green-polo','glenmuir-dark-green-polo','Tops','Glenmuir dark green polo','Dark green','#323A3F','Anchor dark','polo collar','Short-sleeve polo, three-button placket, self collar','Performance wicking pique','Light','Casual',3,'Small tonal chest crest','Size M','Good from the flat-lay','Keep','Darkest green here. Sits between the Masters pine and the Sporte bright green and is the easiest of the three to wear.','core',true,'Stone, khaki, navy, white','-','Green or olive bottoms','GLENMUIR 1891 PERFORMANCE WICKING, size M. Small tonal crest on the left chest.',false,'tops_89_glenmuir-dark-green-polo','tops_89_glenmuir-dark-green-polo_retail',1,false,'Plain',false),

('tops_90_footjoy-grey-pink-stripe-rsgc-polo','footjoy-grey-pink-stripe-rsgc-polo','Tops','FootJoy grey RSGC polo with pink stripe','Grey with pink chest stripe','#898C92','Mid neutral','polo collar','Short-sleeve polo, three-button placket, contrast heather collar with a pink FJ at the tip, pink stripe across the chest and grey marl lower body','Technical jersey','Light','Smart-casual',3,'Royal Sydney - home club, no restriction','FootJoy Athletic Fit, size M','Good from the flat-lay','Keep','Pink crest and pink stripe on grey. The most deliberately styled polo in the batch.','core',true,'Navy, charcoal, stone, white','-','Pink or grey bottoms','FOOTJOY Athletic Fit, size M. Pink FJ on the collar tip, a pink stripe across the chest, and a PINK RSGC crown-and-monogram on the left chest - the only pink crest in the wardrobe.',false,'tops_90_footjoy-grey-pink-stripe-rsgc-polo','tops_90_footjoy-grey-pink-stripe-rsgc-polo_retail',1,false,'Chest stripe',false),
('tops_91_footjoy-woollahra-grey-polo','footjoy-woollahra-grey-polo','Tops','FootJoy light grey Woollahra Representative polo','Light grey','#BDBDC0','Mid neutral','polo collar','Short-sleeve polo, three-button placket, self collar','Technical pique','Light','Smart-casual',4,'WOOLLAHRA GOLF CLUB - REPRESENTATIVE. Home club, no restriction','FootJoy, size M','Good from the flat-lay','Keep','The second Woollahra representative shirt, and the better made of the two. Pale grey takes the white crest well.','core',true,'Navy, charcoal, stone, white','-','Grey bottoms','FOOTJOY, size M. White WOOLLAHRA GOLF CLUB crest with REPRESENTATIVE beneath it on the left chest.',false,'tops_91_footjoy-woollahra-grey-polo','tops_91_footjoy-woollahra-grey-polo_retail',1,false,'Plain',false),

('tops_92_barbaroux-grey-polo','barbaroux-grey-polo','Tops','Golf Club Barbaroux grey polo','Grey','#AAA7A6','Mid neutral','polo collar','Short-sleeve polo, three-button placket, self collar','Technical jersey','Light','Casual',3,'GOLF CLUB BARBAROUX - a visitor souvenir from the Var. Another club''s crest','Size not read','Good from the flat-lay','Keep','The only French club in the wardrobe. Worth keeping for that alone.','core',true,'Navy, charcoal, stone, white','-','Grey bottoms','Tonal oval crest reading GOLF CLUB BARBAROUX over three pine cones on the left chest. A debossed mark at the neck could not be read - NO BRAND ASSERTED. Size unread.',false,'tops_92_barbaroux-grey-polo','tops_92_barbaroux-grey-polo_retail',1,false,'Plain',true),

('tops_93_stone-rsgc-polo','stone-rsgc-polo','Tops','Stone RSGC polo (brand unread)','Stone greige','#E3E0D9','Pale neutral','polo collar','Short-sleeve polo, three-button placket, self collar, fine tonal diamond texture','Technical pique','Light','Smart-casual',4,'Royal Sydney - home club, no restriction','Size not read - no brand or size tag is visible in either photograph','Good from the flat-lay','Keep','Warm stone with a tonal crest. The most understated club polo in the batch and probably the most wearable.','core',true,'Navy, olive, charcoal, white','-','Stone or beige bottoms','Fine tonal diamond texture on a warm stone ground with a TONAL RSGC crown-and-monogram on the left chest. NO BRAND TAG IN FRAME - not guessed. Size unread.',false,'tops_93_stone-rsgc-polo','tops_93_stone-rsgc-polo_retail',1,false,'Diamond texture',true),

('tops_94_gfore-camiral-camo-polo','gfore-camiral-camo-polo','Tops','G/FORE white camo Camiral polo','White with pale grey camo print','#E8E9EA','Pale neutral','polo collar','Short-sleeve polo, three-button placket, self collar with yellow tipping at the inner stand','Technical jersey','Light','Casual',3,'CAMIRAL - a visitor souvenir from Catalunya','Size M','Good from the flat-lay','Keep','Camo in white-on-white, so it reads as texture rather than camouflage. G/FORE is the most expensive label here.','core',true,'Navy, stone, charcoal','-','Anything else patterned','G/FORE, MADE IN VIETNAM, size M. Pale grey camo print on white with yellow tipping inside the collar stand, and CAMIRAL embroidered under a small crest on the left chest. Read at full resolution after a contact sheet made it look like a Nike swoosh - it is not.',false,'tops_94_gfore-camiral-camo-polo','tops_94_gfore-camiral-camo-polo_retail',1,false,'Camo print',false),

('tops_95_abacus-bonville-white-polo','abacus-bonville-white-polo','Tops','abacus white Bonville polo','White','#F2F2F0','Pale neutral','polo collar','Short-sleeve polo, three-button placket, self collar','Technical jersey','Light','Smart-casual',3,'BONVILLE - a visitor souvenir, matching the existing Bonville memorabilia','Size not read - the abacus heat-seal shows no size in frame','Good from the flat-lay. White, so watch the collar','Keep','Bonville again, this time on a shirt rather than a hat. White, so it goes with everything.','core',true,'Navy, stone, charcoal','-','Nothing significant','abacus heat-seal at the neck. Navy BGR crossed-clubs crest with Bonville beneath it on the left chest. Size unread.',false,'tops_95_abacus-bonville-white-polo','tops_95_abacus-bonville-white-polo_retail',1,false,'Plain',false),
('tops_96_adidas-ocean-dunes-white-polo','adidas-ocean-dunes-white-polo','Tops','adidas Ocean Dunes white polo','White with orange, grey and navy chest stripe','#EFEFEE','Pale neutral','polo collar','Short-sleeve polo, three-button placket, contrast orange inner collar stand, wide orange stripe banded in grey across the chest','climacool technical jersey','Light','Casual',2,'OCEAN DUNES, KING ISLAND - a visitor souvenir. Loud enough to be a talking point','Size S, made in Vietnam','Good from the flat-lay','Keep','The boldest block of colour in the batch. King Island is a good story; the orange band is a lot of shirt.','core',true,'Navy, charcoal, stone. Nothing orange','-','Orange, red or patterned bottoms','ADIDAS climacool, size S, made in Vietnam. Ocean Dunes / King Island embroidered on the left chest above a wide orange chest band edged in grey, orange inside the collar stand. ONLY ONE PHOTOGRAPH - the neck label was legible within it.',false,'tops_96_adidas-ocean-dunes-white-polo','tops_96_adidas-ocean-dunes-white-polo_retail',1,false,'Chest stripe',false),

('tops_97_calvin-klein-barnbougle-dunes-polo','calvin-klein-barnbougle-dunes-polo','Tops','Calvin Klein Golf Barnbougle Dunes polo','Cream','#F0EEE7','Pale neutral','polo collar','Short-sleeve polo, three-button placket, self collar with taupe tipping at the shoulder','Technical jersey','Light','Casual',3,'BARNBOUGLE DUNES - a visitor souvenir. The pair to tops_72, which is Lost Farm','Size not read - the Calvin Klein golf label carries no size in frame','Possible grey marks near the placket in the flat-lay - worth a look by hand before it goes out','Keep','The Dunes half of the Barnbougle pair. Cream with taupe tipping is a better-looking shirt than the Lost Farm one.','core',true,'Navy, stone, olive, charcoal','-','Cream or beige bottoms','CALVIN KLEIN GOLF. Barnbougle DUNES embroidered on the left chest, taupe tipping across the shoulder and collar. Size unread. Two or three small grey marks near the placket - noted as possible, not asserted as damage.',false,'tops_97_calvin-klein-barnbougle-dunes-polo','tops_97_calvin-klein-barnbougle-dunes-polo_retail',1,false,'Plain',false),

('tops_98_bcln-white-orange-polo','bcln-white-orange-polo','Tops','BCLN Golf white polo with orange trim','White with orange trim','#F1F1F1','Pale neutral','polo collar','Short-sleeve polo, three-button placket, contrast orange inner collar and placket facing, orange chevron outline on the chest','Technical jersey','Light','Casual',3,'BCLN GOLF shield crest','Size not read - the tag under the collar logo is illegible','Possible small marks near the collar in the flat-lay - worth a look by hand','Keep','Sharp graphic shirt. The orange chevron is unusual enough to be the thing people notice.','core',true,'Navy, charcoal, stone. Nothing orange','-','Orange or red bottoms','BCLN GOLF with a striped shield crest printed inside the orange collar stand. Orange facings and an orange chevron outline on the chest. Size unread. Small marks near the collar - possible, not asserted.',false,'tops_98_bcln-white-orange-polo','tops_98_bcln-white-orange-polo_retail',1,false,'Trim',false),

('tops_99_bermuda-sands-hope-island-polo','bermuda-sands-hope-island-polo','Tops','Bermuda Sands Links Hope Island polo','White with navy, pink and grey bird print','#EFEFF3','Pattern','polo collar','Short-sleeve polo, three-button placket, self collar in the same print','Cotton-blend pique','Light','Casual',2,'LINKS HOPE ISLAND - a visitor souvenir from the Gold Coast','Size not read','Good from the flat-lay','Keep','Seagulls. Cheerful, resort-ish and the second loudest thing in the batch after the Good Good.','core',true,'Navy, stone, white. Nothing else patterned','-','Anything else patterned, and pink bottoms','BERMUDA SANDS at the neck. Navy, pink and grey birds scattered over white, with LINKS HOPE ISLAND embroidered in white on the left chest. The only garment in this batch shot as PNG rather than JPG. Size unread.',false,'tops_99_bermuda-sands-hope-island-polo','tops_99_bermuda-sands-hope-island-polo_retail',1,false,'Bird print',false);

-- Occasions: golf plus casual/weekend for all thirty-nine. None is a work shirt - Max is in a bank.
INSERT INTO item_occasions (item_id, occasion_code)
SELECT id, o FROM items CROSS JOIN (VALUES ('golf'),('casual'),('weekend')) v(o)
WHERE id BETWEEN 'tops_61' AND 'tops_99_zzz'
ON CONFLICT DO NOTHING;

-- Colour provenance. Same method as migration 048, with the white-point fix described in the
-- header: candidates for the white reference now EXCLUDE the garment's own box, so a pale
-- garment can no longer be its own neutral.
INSERT INTO item_field_sources (item_id, field_name, source, note)
SELECT id, 'hex', 'derived',
       'MEASURED against the white table in the same frame, 2026-08-31. White point = 97th percentile per channel of the low-saturation pixels in a frame-interior annulus with the garment box removed; garment = median of the garment box with the darkest quartile and brightest decile discarded. The exclusion of the garment box is new in this batch and was necessary: on the first pass the khaki FootJoy and the peach Under Armour measured as neutral greys because the garment was acting as its own white reference.'
FROM items WHERE id BETWEEN 'tops_61' AND 'tops_99_zzz'
  AND id NOT IN ('tops_68_peter-millar-white-rsgc-polo-m','tops_69_glenmuir-cream-mercerised-polo',
                 'tops_78_woollahra-white-micro-floral-polo','tops_93_stone-rsgc-polo',
                 'tops_94_gfore-camiral-camo-polo','tops_95_abacus-bonville-white-polo',
                 'tops_96_adidas-ocean-dunes-white-polo','tops_97_calvin-klein-barnbougle-dunes-polo',
                 'tops_98_bcln-white-orange-polo','tops_99_bermuda-sands-hope-island-polo')
ON CONFLICT DO NOTHING;

-- The ten near-whites. Same failure as tops_52 and tops_53: on a white or near-white garment the
-- central region is mostly shadow and the method faithfully measures the shadow, returning
-- values between #C0C2BF and #DADCDB. Set near-white by judgement.
INSERT INTO item_field_sources (item_id, field_name, source, note)
SELECT id, 'hex', 'derived',
       'White or near-white garment. Measurement returned a mid grey because it was reading shadow across the cloth, not colour. Hex set near-white by judgement, as on tops_52 and tops_53.'
FROM items WHERE id IN ('tops_68_peter-millar-white-rsgc-polo-m','tops_69_glenmuir-cream-mercerised-polo',
                        'tops_78_woollahra-white-micro-floral-polo','tops_93_stone-rsgc-polo',
                        'tops_94_gfore-camiral-camo-polo','tops_95_abacus-bonville-white-polo',
                        'tops_96_adidas-ocean-dunes-white-polo','tops_97_calvin-klein-barnbougle-dunes-polo',
                        'tops_98_bcln-white-orange-polo','tops_99_bermuda-sands-hope-island-polo')
ON CONFLICT DO NOTHING;

-- Deliberate non-identifications. These follow tops_58: the mark exists, it was zoomed, it could
-- not be read, and nothing was guessed. Marked manual so a re-import cannot quietly fill them in.
INSERT INTO item_field_sources (item_id, field_name, source, note) VALUES
('tops_61_rose-unbranded-polo','notes','manual','Brand UNKNOWN and deliberately blank. The only neck tag in frame is a size tag (M, 100% polyester, made in China); no brand mark appears anywhere on the garment in either photograph. Do not guess a brand into this row.'),
('tops_70_footjoy-khaki-polo','formality_note','manual','A dark navy crest sits on the left chest and was not legible at full resolution. It has NOT been named as Royal Sydney or anything else. Re-shoot the chest if the club matters.'),
('tops_71_nike-charcoal-piped-polo','notes','manual','A small pale script embroidery on the left chest was zoomed and could not be read. No club asserted.'),
('tops_72_barnbougle-lost-farm-charcoal-polo','notes','manual','Brand UNKNOWN. The chest reads Barnbougle LOST FARM but no maker''s label appears in either photograph. Do not guess a brand into this row.'),
('tops_73_royal-melbourne-navy-argyle-polo','notes','manual','Brand UNKNOWN. Royal Melbourne crest read cleanly; no maker''s label in frame. The second photograph is a macro of a hem pocket whose debossed mark could not be read.'),
('tops_78_woollahra-white-micro-floral-polo','notes','manual','ONE PHOTOGRAPH ONLY - no neck label was shot, so brand and size are both unknown. Shoot the label next time this comes out of the drawer.'),
('tops_80_red-unbranded-polo','notes','manual','Brand UNKNOWN. Neck tag reads M/M, MADE IN CHINA and nothing more; the small dark chest logo was zoomed and is not legible. Do not guess.'),
('tops_86_grey-peru-unbranded-polo','notes','manual','Brand UNKNOWN. The black brand tag at the neck is photographed but completely illegible; the size tag beside it reads S, MADE IN PERU. Do not guess.'),
('tops_92_barbaroux-grey-polo','notes','manual','Brand UNKNOWN. Golf Club Barbaroux crest read cleanly; the debossed neck mark could not be read.'),
('tops_93_stone-rsgc-polo','notes','manual','Brand UNKNOWN and size unread - no brand or size tag appears in either photograph.'),
('tops_64_peter-millar-red-interclub-polo-m','fit','manual','Size M read at full resolution off the neck label visible in this garment''s own flat-lay. Its twin tops_62 reads S on a separate label shot taken four seconds after that garment''s flat-lay. Confirmed with Max as two garments, not one shot twice.'),
('tops_62_peter-millar-red-interclub-polo-s','fit','manual','Size S read at full resolution. See tops_64, which is the same shirt in M.'),
('tops_94_gfore-camiral-camo-polo','notes','manual','Brand read at full resolution as G/FORE after the contact sheet suggested Nike - what looked like a swoosh is a camo shape. Chest reads CAMIRAL.'),
('tops_97_calvin-klein-barnbougle-dunes-polo','condition','manual','Possible small grey marks near the placket, seen in a flat, evenly-lit flat-lay. Recorded as possible, not asserted as damage - nothing was inspected by hand.'),
('tops_98_bcln-white-orange-polo','condition','manual','Possible small marks near the collar, seen in a flat, evenly-lit flat-lay. Recorded as possible, not asserted as damage.')
ON CONFLICT DO NOTHING;
