#!/usr/bin/env python3
"""
Corrections to wardrobe.json  —  2026-08-26
Generated by the Cowork wardrobe session after reconciling the catalogue
against the actual contents of G:\\My Drive\\Claude stuff\\Wardrobe Photos\\.

Idempotent. Dry-run by default; pass --commit to write.
Never edits in place: writes <input>.new and leaves the original untouched.

    python patch_wardrobe_20260826.py data/wardrobe.json
    python patch_wardrobe_20260826.py data/wardrobe.json --commit
"""
import json, sys, shutil, pathlib

# ---------------------------------------------------------------- edits
GROUP_NOTE = (" CORRECTED 2026-08-26: the previous note claiming 'the referenced group photo is not "
              "on Drive - this item has no image file' is FALSE. The group photo exists at "
              "Shoes/{fname} and is legible enough to assess from. `noPhoto` stays true here because "
              "it means 'no INDIVIDUAL photo', which is still accurate.")

LOAFERS = "shoes_08_loafers-group_reference.webp"
NIKES   = "shoes_09_nike-trainers-group_reference.webp"

EDITS = {
  # --- the stale flag Claude Code's copy still has wrong -------------
  "trousers_11_black-coated-jeans": {
    "noPhoto": False,
    "photoRef": ("Drive Trousers folder, trousers_11_black-coated-jeans_01..05 "
                 "(label/flat/worn-front/worn-side/worn-back) - filed 2026-08-25"),
  },
  # --- corrections from the 2026-08-26 worn photo -------------------
  "outerwear_02_indindustrie-black-waxed-biker": {
    "condition": ("Good. CORRECTED 2026-08-26 from a worn photo: the earlier 'coating reads "
                  "faded/dusty, needs a clean or a re-wax' assessment was made from hanger shots "
                  "and is WRONG on the body - it reads as proper matte black when worn. Re-wax "
                  "downgraded from blocker to optional."),
    "verdictNote": ("Keep and wear it. Worn 2026-08-26 for the first time in a long while and it "
                    "looked correct with no cleaning first."),
    "careNote": "Waxed cotton - shower-resistant; re-wax eventually, not urgent",
    "_append_notes": (" Back in rotation 2026-08-26. RENDER NOTE: the first AI render lost the "
                      "epaulettes, snap collar tab and chest zip pocket - attach "
                      "outerwear_02_..._02_hanger.jpg as a reference image."),
  },
  "trousers_09_celio-indigo-jeans": {
    "_append_notes": (" 2026-08-26 - NEVER TAILORED. The 2026-08-20 'all trousers tailored' batch "
                      "covered items with verdict `Tailor`; this pair is verdict `Keep` so it was "
                      "skipped, despite `fit` recording '~2cm too long'. Confirmed visually in the "
                      "2026-08-26 worn photo: the hem breaks and pools over the shoe. HEM THIS - "
                      "highest-leverage alteration in the wardrobe, it appears in 4 of the 7 killer "
                      "fits. Also flagged in two independent wear reviews (17 Aug, 26 Aug) as too "
                      "faded for office wear."),
  },
  "trousers_00_decathlon-stone": {
    "_append_notes": (" 2026-08-26 - ANOMALY: a retail render exists (Retail/"
                      "trousers_00_decathlon-stone_retail.jpeg) but there is NO source photograph. "
                      "That render was therefore produced from a written description with no visual "
                      "reference and has never been verified against the actual garment. Treat as "
                      "unverified."),
  },
  # --- the false 'no image file' claim on the five group-shot shoes --
  "shoes_08a_suede-penny-loafer": {
    "photoRef": f"Drive Shoes folder, {LOAFERS} (shared group shot - leftmost pair)",
    "_append_notes": GROUP_NOTE.format(fname=LOAFERS),
  },
  "shoes_08b_tan-loafer": {
    "photoRef": f"Drive Shoes folder, {LOAFERS} (shared group shot - centre pair)",
    "_append_notes": GROUP_NOTE.format(fname=LOAFERS),
  },
  "shoes_08c_megis-driving-moc": {
    "photoRef": f"Drive Shoes folder, {LOAFERS} (shared group shot - rightmost pair)",
    "_append_notes": GROUP_NOTE.format(fname=LOAFERS),
  },
  "shoes_09a_nike-airmax-running": {
    "photoRef": f"Drive Shoes folder, {NIKES} (shared group shot - left pair, grey/neon)",
    "_append_notes": GROUP_NOTE.format(fname=NIKES),
  },
  "shoes_09b_nike-airmax-1": {
    "photoRef": f"Drive Shoes folder, {NIKES} (shared group shot - right pair, olive/white)",
    "_append_notes": GROUP_NOTE.format(fname=NIKES),
  },
}

# Reserved individual prefixes for the two shoes due a reshoot.
# NOT applied by this patch: applying them before the files exist would break
# the only image reference these items currently have. Apply when the shots land.
RESERVED_ON_RESHOOT = {
  "shoes_08a_suede-penny-loafer": "shoes_08a_suede-penny-loafer",
  "shoes_09b_nike-airmax-1":      "shoes_09b_nike-airmax-1",
}

EXPECTED = {"items": 69, "noPhoto_true": 12,
            "verdicts": {"Keep": 45, "Tailor": 10, "Bin": 8, "Replace": 6},
            "scopes": {"core": 65, "out": 4}}

# ---------------------------------------------------------------- run
def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    path = pathlib.Path(sys.argv[1])
    commit = "--commit" in sys.argv
    data = json.loads(path.read_text(encoding="utf-8"))
    by_id = {it["id"]: it for it in data["items"]}

    missing = [k for k in EDITS if k not in by_id]
    if missing:
        sys.exit(f"STOP - ids not found in {path}: {missing}")

    changes = []
    for id_, patch in EDITS.items():
        it = by_id[id_]
        for field, value in patch.items():
            if field == "_append_notes":
                if value.strip() in it.get("notes", ""):
                    continue                        # idempotent
                it["notes"] = it.get("notes", "").rstrip() + value
                changes.append(f"{id_}.notes  += {value.strip()[:70]}...")
            else:
                if it.get(field) == value:
                    continue                        # idempotent
                changes.append(f"{id_}.{field}  {it.get(field)!r} -> {value!r}"[:160])
                it[field] = value

    if data.get("generated") != "2026-08-26":
        changes.append(f"generated  {data.get('generated')!r} -> '2026-08-26'")
        data["generated"] = "2026-08-26"

    # ------------------------------------------------ verification
    items = data["items"]
    got = {
      "items": len(items),
      "noPhoto_true": sum(1 for i in items if i.get("noPhoto") is True),
      "verdicts": {},
      "scopes": {},
    }
    for i in items:
        got["verdicts"][i["verdict"]] = got["verdicts"].get(i["verdict"], 0) + 1
        got["scopes"][i["scope"]] = got["scopes"].get(i["scope"], 0) + 1

    print(f"--- {len(changes)} change(s) ---")
    for c in changes:
        print("  ", c)
    print("\n--- reconciliation ---")
    ok = True
    for k, exp in EXPECTED.items():
        good = got[k] == exp
        ok &= good
        print(f"  {'OK ' if good else 'FAIL'}  {k}: got {got[k]}  expected {exp}")

    print("\n  items still lacking an INDIVIDUAL photo (noPhoto=true):")
    for i in items:
        if i.get("noPhoto") is True:
            shared = "shared group shot" if "group_reference" in (i.get("photoRef") or "") else "NO IMAGE AT ALL"
            print(f"     {i['id']:46s} {i['verdict']:8s} {i['scope']:5s}  {shared}")

    print("\n  reserved prefixes to apply WHEN the reshoots land (not applied now):")
    for k, v in RESERVED_ON_RESHOOT.items():
        print(f"     {k} -> photoPrefix/retailPrefix '{v}' / '{v}_retail'")

    if not ok:
        sys.exit("\nSTOP - reconciliation failed. Do not commit. Investigate the mismatch.")

    out = path.with_suffix(path.suffix + ".new")
    if commit:
        shutil.copy2(path, path.with_suffix(path.suffix + ".bak"))
        out.write_text(json.dumps(data, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"\nWROTE  {out}\nBACKUP {path.with_suffix(path.suffix + '.bak')}"
              f"\nOriginal untouched. Review the diff, then move .new into place yourself.")
    else:
        print("\nDRY RUN - nothing written. Re-run with --commit.")

if __name__ == "__main__":
    main()
