#!/usr/bin/env python3
"""
Corrections to wardrobe.json  —  2026-08-26  (rev 4: + tee renders, grey hex corrected)

Generated by the Cowork wardrobe session after reconciling the catalogue against
the actual contents of G:\\My Drive\\Claude stuff\\Wardrobe Photos\\ and
completing the belt and shoe reshoots.

Supersedes rev 1. Idempotent and safe to run over a rev-1 result — already-applied
edits are skipped. Dry-run by default; pass --commit to write.
Never edits in place: writes <input>.new, backs up to <input>.bak.

    python patch_wardrobe_20260826.py data/wardrobe.json
    python patch_wardrobe_20260826.py data/wardrobe.json --commit
"""
import json, sys, shutil, pathlib

# ---------------------------------------------------------------- deletions
# trousers_00_decathlon-stone is a PHANTOM DUPLICATE of trousers_01_decathlon-beige.
# Confirmed by Max 2026-08-26 after physically counting: he owns ONE beige/stone
# Decathlon chino, not two. He re-sent photos of what he believed was the
# unphotographed pair; they were byte-identical to trousers_01's label and flatlay,
# on Drive since 5 Aug. The label reads US W33 L33 but trousers_01 was recorded as
# "US W31 L33" — that transcription error was the ONLY field distinguishing the two.
# trousers_00 never had a photograph; its retail render came from a text description.
# The .bak written by --commit is the undo. Nothing downstream references this id.
DELETE_IDS = ["trousers_00_decathlon-stone"]
ORPHANED_BY_DELETE = [
    "Retail/trousers_00_decathlon-stone_retail.jpeg",
    "Shoes/shoes_08_loafers-group_reference.webp        (superseded by individual shots)",
    "Shoes/shoes_09_nike-trainers-group_reference.webp  (superseded by individual shots)",
]

GROUP_NOTE_OLD = "the referenced group photo is not on Drive"

EDITS = {
  # ---- stale flag in older copies --------------------------------
  "trousers_11_black-coated-jeans": {
    "noPhoto": False,
    "photoRef": ("Drive Trousers folder, trousers_11_black-coated-jeans_01..05 "
                 "(label/flat/worn-front/worn-side/worn-back) - filed 2026-08-25"),
  },
  # ---- corrections from the 2026-08-26 worn photo -----------------
  "outerwear_02_indindustrie-black-waxed-biker": {
    "condition": ("Good. CORRECTED 2026-08-26 from a worn photo: the earlier 'coating reads "
                  "faded/dusty, needs a clean or a re-wax' assessment was made from hanger shots "
                  "and is WRONG on the body - it reads as proper matte black when worn. Re-wax "
                  "downgraded from blocker to optional."),
    "verdictNote": ("Keep and wear it. Worn 2026-08-26 for the first time in a long while and it "
                    "looked correct with no cleaning first."),
    "careNote": "Waxed cotton - shower-resistant; re-wax eventually, not urgent",
    "_append_notes": (" Back in rotation 2026-08-26. RENDER NOTE: the first AI render lost the "
                      "epaulettes, snap collar tab and chest zip pocket - attach "
                      "outerwear_02_..._02_hanger.jpg as a reference image."),
  },
  "trousers_09_celio-indigo-jeans": {
    "_append_notes": (" 2026-08-26 - NEVER TAILORED. The 2026-08-20 'all trousers tailored' batch "
                      "covered items with verdict `Tailor`; this pair is verdict `Keep` so it was "
                      "skipped, despite `fit` recording '~2cm too long'. Confirmed visually in the "
                      "2026-08-26 worn photo: the hem breaks and pools over the shoe. HEM THIS - "
                      "highest-leverage alteration in the wardrobe, it appears in 4 of the 7 killer "
                      "fits. Flagged as too faded for office wear in two independent wear reviews."),
  },
  "trousers_01_decathlon-beige": {
    "fit": "Waist/seat/thigh correct; length correct, light break - best fitting chino owned",
    "_append_notes": (" SIZE CORRECTED 2026-08-26 from the care label photo: previously recorded "
                      "'US W31 L33'. The label reads EU M (L33) / US W33 L33 / FR 42 / CC 347067. "
                      "The W31 was a transcription error, and it was the only field distinguishing "
                      "this item from the phantom trousers_00_decathlon-stone, now deleted."),
  },

  # ================ NEW IN REV 2 — belt shoot 2026-08-26 ============
  "belts_06_argentina-perforated-brown": {
    "noPhoto": False,
    "photoRef": "Drive Belts folder, belts_06_argentina-perforated-brown_01_full / _02_buckle - shot 2026-08-26",
  },
  "belts_07_marki-navy-white-webbing": {
    "noPhoto": False,
    "photoRef": ("Drive Belts folder, belts_07_marki-navy-white-webbing_01_full / _02_buckle / "
                 "_03_underside - shot 2026-08-26"),
  },
  "belts_09_black-ratchet-dress": {
    "noPhoto": False,
    "photoRef": ("Drive Belts folder, belts_09_black-ratchet-dress_01_full / _02_buckle / "
                 "_03_underside - shot 2026-08-26"),
    "_append_notes": (" 2026-08-26: underside carries blind black-on-black embossing, only "
                      "'...genuine cowhide leather...' legible. No maker's mark. Defining feature "
                      "for identification: NO HOLES in the strap - it adjusts by an internal "
                      "toothed track."),
  },
  "belts_11_black-classic-pin-buckle": {
    "noPhoto": False,
    "photoRef": ("Drive Belts folder, belts_11_black-classic-pin-buckle_01_full / _02_buckle / "
                 "_03_underside - shot 2026-08-26"),
    "_append_notes": (" BRAND IDENTIFIED 2026-08-26 from the underside stamp, previously recorded "
                      "as 'gone faint / unreadable'. It reads: H&M, size M, 85-95 (cm waist range), "
                      "article 304970. Useful when replacing it."),
  },
  "belts_05_zara-dark-brown-distressed": {
    "_append_notes": (" 2026-08-26 - NOT LOCATED. Max gathered every belt he owns for the reshoot "
                      "and this one did not appear. Verdict was already Replace. Treat as probably "
                      "disposed of, but NOT deleted - absence is weaker evidence than the proof "
                      "that removed trousers_00. Confirm with Max before removing."),
  },
  "belts_10_van-heusen-black-plaque": {
    "_append_notes": (" 2026-08-26 - NOT LOCATED. Max reported he could not find it, then gathered "
                      "every belt he owns for the reshoot and it did not appear. Verdict was already "
                      "Replace. Treat as probably disposed of, but NOT deleted. Confirm with Max."),
  },

  # ================ NEW IN REV 2 — shoe shoot 2026-08-26 ===========
  # All five previously shared two group photoPrefixes, which is why none of them
  # ever rendered individually. Each now has its own prefix and its own frames.
  "shoes_08a_suede-penny-loafer": {
    "noPhoto": False,
    "photoPrefix": "shoes_08a_suede-penny-loafer",
    "retailPrefix": "shoes_08a_suede-penny-loafer_retail",
    "photoRef": "Drive Shoes folder, shoes_08a_suede-penny-loafer_pair-angled / _pair-side - shot 2026-08-26",
  },
  "shoes_08b_tan-loafer": {
    "noPhoto": False,
    "photoPrefix": "shoes_08b_tan-loafer",
    "retailPrefix": "shoes_08b_tan-loafer_retail",
    "photoRef": "Drive Shoes folder, shoes_08b_tan-loafer_pair-angled / _pair-side - shot 2026-08-26",
    "colour": "Dark chocolate brown (pebbled leather)",
    "hex": "#4A3B31",
    "name": "Dark brown moccasin loafer",
    "_append_notes": (" 🔴 TWO RECORD ERRORS CORRECTED 2026-08-26 from individual photos. (1) NOT a "
                      "penny loafer - the vamp is a single unbroken panel with no strap, no saddle "
                      "band and no keyhole slot. It is a plain-vamp venetian slip-on moccasin with "
                      "a hand-stitched apron seam and a small raised leather tab at the throat. "
                      "(2) NOT tan - the leather is dark chocolate brown and pebbled. The id and "
                      "photoPrefix keep the '-tan-loafer' stem because the photos are already filed "
                      "under it and ids are never renumbered. Condition confirms the Bin verdict: "
                      "leather dried and crazed, pale abrasion right around the sole edge and toe, "
                      "insole worn black."),
  },
  "shoes_08c_megis-driving-moc": {
    "noPhoto": False,
    "photoPrefix": "shoes_08c_megis-driving-moc",
    "retailPrefix": "shoes_08c_megis-driving-moc_retail",
    "photoRef": "Drive Shoes folder, shoes_08c_megis-driving-moc_pair-angled / _pair-side - shot 2026-08-26",
    "_append_notes": (" 2026-08-26: individual photos show this in noticeably better condition than "
                      "the group shot suggested - deep even nap, clean cream stitching, sole barely "
                      "worn. Its scope='out' (holiday only) was set before there was a decent photo. "
                      "Worth Max reconsidering whether a navy suede driving moc is really out of "
                      "scope for a casual office. Not changed here - his call."),
  },
  "shoes_09a_nike-airmax-running": {
    "noPhoto": False,
    "photoPrefix": "shoes_09a_nike-airmax-running",
    "retailPrefix": "shoes_09a_nike-airmax-running_retail",
    "photoRef": "Drive Shoes folder, shoes_09a_nike-airmax-running_pair-angled / _pair-side - shot 2026-08-26",
  },
  "shoes_09b_nike-airmax-1": {
    "noPhoto": False,
    "photoPrefix": "shoes_09b_nike-airmax-1",
    "retailPrefix": "shoes_09b_nike-airmax-1_retail",
    "photoRef": "Drive Shoes folder, shoes_09b_nike-airmax-1_pair-angled / _pair-side - shot 2026-08-26",
    "_append_notes": (" 2026-08-26: photographed and rendered WITHOUT being cleaned first - grey "
                      "scuffing across the toe and along the white midsole is visible in both the "
                      "photo and the render. Honest, but unflattering for a Keep/core shoe. Clean "
                      "and reshoot when convenient."),
  },
}

# ---------------------------------------------------------------- additions
# Max owns five plain crew tees that have never been logged. NINE V-neck knits
# were unwearable without them, which is why no fit in the first 17 used a
# V-neck; eight of the 20 in fits-batch-2.md now do.
#
# These MUST exist before fits-batch-2.md is imported or nine fits will fail on
# unresolved item references.
#
# ⚠️ COLOURS AND HEXES ARE ASSUMED, NOT VERIFIED. Max listed the colours; the
# garments have never been photographed. Every one carries
# `unconfirmed: true` — surface that in the UI and clear it once they are shot.
_TEE = dict(cat="Tops", neck="crew", cut="Standard fit crew-neck t-shirt",
            material="Cotton jersey (composition unverified)", weight="Light-Mid",
            formality="Casual", fit="unverified", condition="unverified",
            verdict="Keep", verdictNote="Base layer under the nine V-neck knits. Never logged until 2026-08-26.",
            scope="core", worksAlone=True,
            pairs="Worn under any V-neck knit; white suits all of them",
            layer="Base layer - the tee fills the V opening",
            avoid="A tee the same colour as the knit over it",
            warmth=1, weatherproof={"rain": False, "wind": False},
            careNote="Machine wash", noPhoto=True, unconfirmed=True,
            photoRef=("NOT PHOTOGRAPHED. A generated retail render exists for white/grey/black in "
                      "Retail\\, but there is no photograph of the actual garment - fit, condition "
                      "and material remain unverified. Treat as render-only."))

ADD_ITEMS = [
  dict(_TEE, id="tees_01_white-crew", slug="tees_01_white-crew", name="White crew tee",
       colour="White", hex="#F2F2EF", role="Pale neutral",
       photoPrefix="tees_01_white-crew", retailPrefix="tees_01_white-crew_retail",
       notes="The default base layer - used in 8 of the 20 fits in fits-batch-2.md."),
  dict(_TEE, id="tees_02_grey-crew", slug="tees_02_grey-crew", name="Grey crew tee",
       colour="Mid grey (heather marl)", hex="#A6A6A6", role="Neutral",
       photoPrefix="tees_02_grey-crew", retailPrefix="tees_02_grey-crew_retail",
       notes="Quieter alternative to white under a slate or blue V-neck. HEX MEASURED from the retail render 2026-08-26 (#A6A6A6) - it is a heather marl, lighter and more neutral than the #8E9095 originally assumed."),
  dict(_TEE, id="tees_03_black-crew", slug="tees_03_black-crew", name="Black crew tee",
       colour="Black", hex="#1E1E1E", role="Anchor dark",
       photoPrefix="tees_03_black-crew", retailPrefix="tees_03_black-crew_retail",
       notes="Under dark knits where a white triangle would cut the colour in two."),
  dict(_TEE, id="tees_04_green-crew", slug="tees_04_green-crew", name="Green crew tee",
       colour="Green", hex="#4E6B52", role="Statement",
       photoPrefix="tees_04_green-crew", retailPrefix="tees_04_green-crew_retail",
       notes="Strong colour - better worn alone than under a V-neck. Alternate only in fits-batch-2.md."),
  dict(_TEE, id="tees_05_red-crew", slug="tees_05_red-crew", name="Red crew tee",
       colour="Red", hex="#9C3535", role="Statement",
       photoPrefix="tees_05_red-crew", retailPrefix="tees_05_red-crew_retail",
       notes="Strong colour - better worn alone than under a V-neck. Not used in any current fit."),
]

EXPECTED = {"items": 73, "noPhoto_true": 7,
            "verdicts": {"Keep": 50, "Tailor": 9, "Bin": 8, "Replace": 6},
            "scopes": {"core": 69, "out": 4}}

# ---------------------------------------------------------------- run
def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    path = pathlib.Path(sys.argv[1])
    commit = "--commit" in sys.argv
    data = json.loads(path.read_text(encoding="utf-8"))
    by_id = {it["id"]: it for it in data["items"]}

    missing = [k for k in EDITS if k not in by_id]
    if missing:
        sys.exit(f"STOP - ids not found in {path}: {missing}")

    changes = []
    for id_, patch in EDITS.items():
        it = by_id[id_]
        for field, value in patch.items():
            if field == "_append_notes":
                if value.strip()[:60] in it.get("notes", ""):
                    continue                          # idempotent
                it["notes"] = it.get("notes", "").rstrip() + value
                changes.append(f"{id_}.notes  += {value.strip()[:64]}...")
            else:
                if it.get(field) == value:
                    continue                          # idempotent
                changes.append(f"{id_}.{field}  {str(it.get(field))[:40]!r} -> {str(value)[:60]!r}")
                it[field] = value

    for dead in DELETE_IDS:
        if dead in by_id:
            data["items"] = [i for i in data["items"] if i["id"] != dead]
            changes.append(f"DELETED ITEM  {dead}  (phantom duplicate of trousers_01)")

    have = {i["id"] for i in data["items"]}
    for new in ADD_ITEMS:
        if new["id"] not in have:
            data["items"].append(dict(new))
            changes.append(f"ADDED ITEM    {new['id']}  ({new['colour']}, unconfirmed)")

    if data.get("generated") != "2026-08-26":
        changes.append(f"generated  {data.get('generated')!r} -> '2026-08-26'")
        data["generated"] = "2026-08-26"

    # ------------------------------------------------ verification
    items = data["items"]
    got = {"items": len(items),
           "noPhoto_true": sum(1 for i in items if i.get("noPhoto") is True),
           "verdicts": {}, "scopes": {}}
    for i in items:
        got["verdicts"][i["verdict"]] = got["verdicts"].get(i["verdict"], 0) + 1
        got["scopes"][i["scope"]] = got["scopes"].get(i["scope"], 0) + 1

    print(f"--- {len(changes)} change(s) ---")
    for c in changes:
        print("  ", c)

    print("\n--- reconciliation ---")
    ok = True
    for k, exp in EXPECTED.items():
        good = got[k] == exp
        ok &= good
        print(f"  {'OK ' if good else 'FAIL'}  {k}: got {got[k]}  expected {exp}")

    stale = [i["id"] for i in items if GROUP_NOTE_OLD in (i.get("notes") or "")
             or GROUP_NOTE_OLD in (i.get("photoRef") or "")]
    if stale:
        print(f"\n  WARNING - these still carry the false 'group photo is not on Drive' claim: {stale}")

    print("\n  items without a photo (noPhoto=true):")
    for i in items:
        if i.get("noPhoto") is True:
            why = "UNCONFIRMED - never photographed" if i.get("unconfirmed") else "not located 2026-08-26"
            print(f"     {i['id']:46s} {i['verdict']:8s} {i['scope']:5s}  {why}")

    print("\n  files orphaned by this patch - park, do not silently delete:")
    for f in ORPHANED_BY_DELETE:
        print(f"     {f}")

    if not ok:
        sys.exit("\nSTOP - reconciliation failed. Do not commit. Investigate the mismatch.")

    out = path.with_suffix(path.suffix + ".new")
    if commit:
        shutil.copy2(path, path.with_suffix(path.suffix + ".bak"))
        out.write_text(json.dumps(data, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"\nWROTE  {out}\nBACKUP {path.with_suffix(path.suffix + '.bak')}"
              f"\nOriginal untouched. Review the diff, then move .new into place yourself.")
    else:
        print("\nDRY RUN - nothing written. Re-run with --commit.")

if __name__ == "__main__":
    main()
